openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: https://d5die7nqo05tbfampele.apigw.yandexcloud.net
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: itis-2022-2023-vvot33-faces
        object: '{face}'
        service_account_id: ajeqlff7kr0kic9t1ai2
      parameters:
      - explode: false
        in: query
        name: face
        required: true
        schema:
          type: string
        style: simple